name: Deploy to Netcup

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: jkrieg.eu
          username: hosting173047
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd jkrieg.eu/httpdocs/
            git pull origin main
